theme: osuny
_merge: deep
params:
  summary:
    position: hero
  breadcrumb:
    position: after-hero
  search:
    active: true
  logo:
    header: ''
    footer: ''
  home:
    head:
      title: site
  share_links:
    enabled: false

  # SECTIONS
  default:
    index:
      taxonomies:
        display: false
        show_name: false
    single:
      meta:
        position: none
        options:
          authors: false
          dates: false
          published_at: false
          reading_time: false
          share: false
          taxonomies: false
          updated_at: false
          with_labels: false
      taxonomies: # for organizations, persons, events and exhibitions (to be removed with meta)
        position: none
        show_name: false

  categories:
    index:
      layout: list

  pages:
    index:
      layout: list
      options:
        categories: false
    single:
      taxonomies:
        position: none
        
  projects:
    index:
      layout: list
      options:
        categories: false
    single:
      meta:
        options:
          year: false
      share_links:
        enabled: false