[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/projets/sculpture/index.html"
to = "/travaux/sculpture/"

[[redirects]]
from = "/projets/2023-multitude/index.html"
to = "/travaux/2023-multitude/"

[[redirects]]
from = "/projets/image/index.html"
to = "/travaux/image/"

[[redirects]]
from = "/projets/2023-ensemble-cube/index.html"
to = "/travaux/2023-ensemble-cube/"

[[redirects]]
from = "/compagnonnage/index.html"
to = "/expos/compagnonnage/"

[[redirects]]
from = "/chutes/index.html"
to = "/expos/chutes/"

[[redirects]]
from = "/batons-rompus/index.html"
to = "/expos/batons-rompus/"

[[redirects]]
from = "/traces-eventuelles-de-graisse/index.html"
to = "/expos/traces-eventuelles-de-graisse/"

[[redirects]]
from = "/expo/index.html"
to = "/exposition/"

[[redirects]]
from = "/projets/index.html"
to = "/travaux/"

